/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academicrecordmaintenancesystem;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lerum
 */
public class frmFacultyClerk extends javax.swing.JFrame {

    // Variables
    private JFrame frame;
    Color DefaultColor, ClickedColor;
    
    /**
     * Creates new form frmRegistrarClerk
     */
    
    public frmFacultyClerk() {
        initComponents();
        
        // Set Form To Full Screen Automatically
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Panel Defualt Colur 
        DefaultColor = new Color(0,0,0);
        
        // Panel Colour When Clicked
        ClickedColor = new Color(204,204,204);
        
        // Panels All Set To Default Colour When System Starts
        pnlCreateProfile.setBackground(DefaultColor);
        pnlEditProfiles.setBackground(DefaultColor);
        pnlAchievements.setBackground(DefaultColor);
        pnlLogOut.setBackground(DefaultColor);
        
    }
    
    // Beginning Of The mLogout Method
    private void mLogout(){
        
        frame = new JFrame("Logout");
        
        if(JOptionPane.showConfirmDialog(frame, "Are You Sure You Want To Logout?", "LRM College", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            
            // Display Form
            frmLoginPage menu = new frmLoginPage();
            menu.show();
            dispose();
            
        }
        
    }
    // End Of The mLogout Method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblRegistrarClerk = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        pnlAchievements = new javax.swing.JPanel();
        lblAchievements = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        pnlCreateProfile = new javax.swing.JPanel();
        lblCreateProfile = new javax.swing.JLabel();
        pnlEditProfiles = new javax.swing.JPanel();
        lblEditProfiles = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LRM College");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDashboard.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("DASHBOARD");

        lblRegistrarClerk.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblRegistrarClerk.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarClerk.setText("Faculty Clerk");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistrarClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(728, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistrarClerk)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlAchievements.setBackground(new java.awt.Color(0, 0, 0));
        pnlAchievements.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlAchievements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAchievementsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAchievementsMousePressed(evt);
            }
        });

        lblAchievements.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAchievements.setForeground(new java.awt.Color(255, 255, 255));
        lblAchievements.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAchievements.setText("ACHIEVEMENTS");

        javax.swing.GroupLayout pnlAchievementsLayout = new javax.swing.GroupLayout(pnlAchievements);
        pnlAchievements.setLayout(pnlAchievementsLayout);
        pnlAchievementsLayout.setHorizontalGroup(
            pnlAchievementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAchievementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAchievements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAchievementsLayout.setVerticalGroup(
            pnlAchievementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAchievementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAchievements, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLogOut.setBackground(new java.awt.Color(0, 0, 0));
        pnlLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlLogOut.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLogOutMousePressed(evt);
            }
        });

        lblLogOut.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setText("LOGOUT");

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCreateProfile.setBackground(new java.awt.Color(0, 0, 0));
        pnlCreateProfile.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlCreateProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCreateProfileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCreateProfileMousePressed(evt);
            }
        });

        lblCreateProfile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCreateProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreateProfile.setText("CREATE PROFILE");

        javax.swing.GroupLayout pnlCreateProfileLayout = new javax.swing.GroupLayout(pnlCreateProfile);
        pnlCreateProfile.setLayout(pnlCreateProfileLayout);
        pnlCreateProfileLayout.setHorizontalGroup(
            pnlCreateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCreateProfileLayout.setVerticalGroup(
            pnlCreateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlEditProfiles.setBackground(new java.awt.Color(0, 0, 0));
        pnlEditProfiles.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlEditProfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditProfilesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlEditProfilesMousePressed(evt);
            }
        });

        lblEditProfiles.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEditProfiles.setForeground(new java.awt.Color(255, 255, 255));
        lblEditProfiles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditProfiles.setText("EDIT PROFILES");

        javax.swing.GroupLayout pnlEditProfilesLayout = new javax.swing.GroupLayout(pnlEditProfiles);
        pnlEditProfiles.setLayout(pnlEditProfilesLayout);
        pnlEditProfilesLayout.setHorizontalGroup(
            pnlEditProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditProfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditProfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEditProfilesLayout.setVerticalGroup(
            pnlEditProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditProfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditProfiles, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academicrecordmaintenancesystem/School Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEditProfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAchievements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlCreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(pnlCreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEditProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAchievements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(pnlLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pnlMain.setBackground(new java.awt.Color(204, 204, 204));
        pnlMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMain.setPreferredSize(new java.awt.Dimension(1660, 950));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCreateProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateProfileMouseClicked
        
        // Display Form
        frmCreateProfile menu = new frmCreateProfile();
        pnlMain.removeAll();
        pnlMain.add(menu).setVisible(true);
        
    }//GEN-LAST:event_pnlCreateProfileMouseClicked

    private void pnlCreateProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateProfileMousePressed
                
        // Change The Colour Of pnlCreateProfile
        pnlCreateProfile.setBackground(ClickedColor);
        pnlEditProfiles.setBackground(DefaultColor);
        pnlAchievements.setBackground(DefaultColor);
        pnlLogOut.setBackground(DefaultColor);
        
    }//GEN-LAST:event_pnlCreateProfileMousePressed

    private void pnlEditProfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditProfilesMouseClicked
                
        // Display Form
        frmEditProfiles menu = new frmEditProfiles();
        pnlMain.removeAll();
        pnlMain.add(menu).setVisible(true);
        
    }//GEN-LAST:event_pnlEditProfilesMouseClicked

    private void pnlEditProfilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditProfilesMousePressed
                
        // Change The Colour Of pnlEditProfiles
        pnlCreateProfile.setBackground(DefaultColor);
        pnlEditProfiles.setBackground(ClickedColor);
        pnlAchievements.setBackground(DefaultColor);
        pnlLogOut.setBackground(DefaultColor);
        
    }//GEN-LAST:event_pnlEditProfilesMousePressed

    private void pnlAchievementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAchievementsMouseClicked
        
        // Display Form
        frmAchievements menu = new frmAchievements();
        pnlMain.removeAll();
        pnlMain.add(menu).setVisible(true); 
        
    }//GEN-LAST:event_pnlAchievementsMouseClicked

    private void pnlAchievementsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAchievementsMousePressed
        
        // Change The Colour Of pnlAchievements
        pnlCreateProfile.setBackground(DefaultColor);
        pnlEditProfiles.setBackground(DefaultColor);
        pnlAchievements.setBackground(ClickedColor);
        pnlLogOut.setBackground(DefaultColor);
        
    }//GEN-LAST:event_pnlAchievementsMousePressed

    private void pnlLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogOutMouseClicked
                
        mLogout();
    
    }//GEN-LAST:event_pnlLogOutMouseClicked

    private void pnlLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogOutMousePressed
                // Change The Colour Of pnlLogOut
        pnlCreateProfile.setBackground(DefaultColor);
        pnlEditProfiles.setBackground(DefaultColor);
        pnlAchievements.setBackground(DefaultColor);
        pnlLogOut.setBackground(ClickedColor);

    }//GEN-LAST:event_pnlLogOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacultyClerk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAchievements;
    private javax.swing.JLabel lblCreateProfile;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEditProfiles;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblRegistrarClerk;
    private javax.swing.JPanel pnlAchievements;
    private javax.swing.JPanel pnlCreateProfile;
    private javax.swing.JPanel pnlEditProfiles;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
